#!/usr/bin/env python3
"""
Data Enrichment Module for Project Revelare
Contains functions for enriching extracted indicators with additional metadata.
"""

import time
from typing import Dict, Any, Optional
from revelare.utils.logger import get_logger

logger = get_logger(__name__)


class DataEnricher:
    """Central class for data enrichment operations."""

    @staticmethod
    def enrich_area_code(area_code: str) -> Dict[str, Any]:
        """Enrich area code with location information."""
        try:
            # Import here to avoid circular dependencies
            from data_enhancer import DataEnhancer
            enhancer = DataEnhancer()
            return enhancer.enrich_area_code(area_code)
        except Exception as e:
            logger.debug(f"Area code enrichment failed for {area_code}: {e}")
            return DataEnricher._enrich_area_code_fallback(area_code)

    @staticmethod
    def _enrich_area_code_fallback(area_code: str) -> Dict[str, Any]:
        """Fallback area code enrichment using local database."""
        # Common US area codes with their locations
        area_code_data = {
            '803': {'state': 'South Carolina', 'city': 'Columbia', 'timezone': 'EST'},
            '212': {'state': 'New York', 'city': 'New York', 'timezone': 'EST'},
            '213': {'state': 'California', 'city': 'Los Angeles', 'timezone': 'PST'},
            '214': {'state': 'Texas', 'city': 'Dallas', 'timezone': 'CST'},
            '215': {'state': 'Pennsylvania', 'city': 'Philadelphia', 'timezone': 'EST'},
            '216': {'state': 'Ohio', 'city': 'Cleveland', 'timezone': 'EST'},
            '217': {'state': 'Illinois', 'city': 'Springfield', 'timezone': 'CST'},
            '218': {'state': 'Minnesota', 'city': 'Duluth', 'timezone': 'CST'},
            '219': {'state': 'Indiana', 'city': 'Gary', 'timezone': 'CST'},
            '224': {'state': 'Illinois', 'city': 'Evanston', 'timezone': 'CST'},
            '225': {'state': 'Louisiana', 'city': 'Baton Rouge', 'timezone': 'CST'},
            '228': {'state': 'Mississippi', 'city': 'Gulfport', 'timezone': 'CST'},
            '229': {'state': 'Georgia', 'city': 'Albany', 'timezone': 'EST'},
            '231': {'state': 'Michigan', 'city': 'Muskegon', 'timezone': 'EST'},
            '234': {'state': 'Ohio', 'city': 'Akron', 'timezone': 'EST'},
            '239': {'state': 'Florida', 'city': 'Fort Myers', 'timezone': 'EST'},
            '240': {'state': 'Maryland', 'city': 'Hagerstown', 'timezone': 'EST'},
            '248': {'state': 'Michigan', 'city': 'Troy', 'timezone': 'EST'},
            '251': {'state': 'Alabama', 'city': 'Mobile', 'timezone': 'CST'},
            '252': {'state': 'North Carolina', 'city': 'Greenville', 'timezone': 'EST'},
            '253': {'state': 'Washington', 'city': 'Tacoma', 'timezone': 'PST'},
            '254': {'state': 'Texas', 'city': 'Killeen', 'timezone': 'CST'},
            '256': {'state': 'Alabama', 'city': 'Huntsville', 'timezone': 'CST'},
            '260': {'state': 'Indiana', 'city': 'Fort Wayne', 'timezone': 'EST'},
            '262': {'state': 'Wisconsin', 'city': 'Kenosha', 'timezone': 'CST'},
            '267': {'state': 'Pennsylvania', 'city': 'Philadelphia', 'timezone': 'EST'},
            '269': {'state': 'Michigan', 'city': 'Kalamazoo', 'timezone': 'EST'},
            '270': {'state': 'Kentucky', 'city': 'Bowling Green', 'timezone': 'CST'},
            '276': {'state': 'Virginia', 'city': 'Bristol', 'timezone': 'EST'},
            '281': {'state': 'Texas', 'city': 'Houston', 'timezone': 'CST'},
            '301': {'state': 'Maryland', 'city': 'Hagerstown', 'timezone': 'EST'},
            '302': {'state': 'Delaware', 'city': 'Wilmington', 'timezone': 'EST'},
            '303': {'state': 'Colorado', 'city': 'Denver', 'timezone': 'MST'},
            '304': {'state': 'West Virginia', 'city': 'Charleston', 'timezone': 'EST'},
            '305': {'state': 'Florida', 'city': 'Miami', 'timezone': 'EST'},
            '307': {'state': 'Wyoming', 'city': 'Cheyenne', 'timezone': 'MST'},
            '308': {'state': 'Nebraska', 'city': 'North Platte', 'timezone': 'CST'},
            '309': {'state': 'Illinois', 'city': 'Peoria', 'timezone': 'CST'},
            '310': {'state': 'California', 'city': 'Beverly Hills', 'timezone': 'PST'},
            '312': {'state': 'Illinois', 'city': 'Chicago', 'timezone': 'CST'},
            '313': {'state': 'Michigan', 'city': 'Detroit', 'timezone': 'EST'},
            '314': {'state': 'Missouri', 'city': 'St. Louis', 'timezone': 'CST'},
            '315': {'state': 'New York', 'city': 'Syracuse', 'timezone': 'EST'},
            '316': {'state': 'Kansas', 'city': 'Wichita', 'timezone': 'CST'},
            '317': {'state': 'Indiana', 'city': 'Indianapolis', 'timezone': 'EST'},
            '318': {'state': 'Louisiana', 'city': 'Shreveport', 'timezone': 'CST'},
            '319': {'state': 'Iowa', 'city': 'Cedar Rapids', 'timezone': 'CST'},
            '320': {'state': 'Minnesota', 'city': 'St. Cloud', 'timezone': 'CST'},
            '321': {'state': 'Florida', 'city': 'Cocoa', 'timezone': 'EST'},
            '323': {'state': 'California', 'city': 'Los Angeles', 'timezone': 'PST'},
            '325': {'state': 'Texas', 'city': 'Abilene', 'timezone': 'CST'},
            '330': {'state': 'Ohio', 'city': 'Akron', 'timezone': 'EST'},
            '331': {'state': 'Illinois', 'city': 'Aurora', 'timezone': 'CST'},
            '334': {'state': 'Alabama', 'city': 'Montgomery', 'timezone': 'CST'},
            '336': {'state': 'North Carolina', 'city': 'Greensboro', 'timezone': 'EST'},
            '337': {'state': 'Louisiana', 'city': 'Lafayette', 'timezone': 'CST'},
            '339': {'state': 'Massachusetts', 'city': 'Boston', 'timezone': 'EST'},
            '347': {'state': 'New York', 'city': 'New York', 'timezone': 'EST'},
            '351': {'state': 'Massachusetts', 'city': 'Lowell', 'timezone': 'EST'},
            '352': {'state': 'Florida', 'city': 'Gainesville', 'timezone': 'EST'},
            '360': {'state': 'Washington', 'city': 'Olympia', 'timezone': 'PST'},
            '361': {'state': 'Texas', 'city': 'Corpus Christi', 'timezone': 'CST'},
            '364': {'state': 'Kentucky', 'city': 'Bowling Green', 'timezone': 'CST'},
            '380': {'state': 'Ohio', 'city': 'Columbus', 'timezone': 'EST'},
            '385': {'state': 'Utah', 'city': 'Salt Lake City', 'timezone': 'MST'},
            '386': {'state': 'Florida', 'city': 'Daytona Beach', 'timezone': 'EST'},
            '401': {'state': 'Rhode Island', 'city': 'Providence', 'timezone': 'EST'},
            '402': {'state': 'Nebraska', 'city': 'Omaha', 'timezone': 'CST'},
            '404': {'state': 'Georgia', 'city': 'Atlanta', 'timezone': 'EST'},
            '405': {'state': 'Oklahoma', 'city': 'Oklahoma City', 'timezone': 'CST'},
            '406': {'state': 'Montana', 'city': 'Billings', 'timezone': 'MST'},
            '407': {'state': 'Florida', 'city': 'Orlando', 'timezone': 'EST'},
            '408': {'state': 'California', 'city': 'San Jose', 'timezone': 'PST'},
            '409': {'state': 'Texas', 'city': 'Beaumont', 'timezone': 'CST'},
            '410': {'state': 'Maryland', 'city': 'Baltimore', 'timezone': 'EST'},
            '412': {'state': 'Pennsylvania', 'city': 'Pittsburgh', 'timezone': 'EST'},
            '413': {'state': 'Massachusetts', 'city': 'Springfield', 'timezone': 'EST'},
            '414': {'state': 'Wisconsin', 'city': 'Milwaukee', 'timezone': 'CST'},
            '415': {'state': 'California', 'city': 'San Francisco', 'timezone': 'PST'},
            '417': {'state': 'Missouri', 'city': 'Springfield', 'timezone': 'CST'},
            '419': {'state': 'Ohio', 'city': 'Toledo', 'timezone': 'EST'},
            '423': {'state': 'Tennessee', 'city': 'Chattanooga', 'timezone': 'EST'},
            '424': {'state': 'California', 'city': 'Los Angeles', 'timezone': 'PST'},
            '425': {'state': 'Washington', 'city': 'Bellevue', 'timezone': 'PST'},
            '430': {'state': 'Texas', 'city': 'Tyler', 'timezone': 'CST'},
            '432': {'state': 'Texas', 'city': 'Midland', 'timezone': 'CST'},
            '434': {'state': 'Virginia', 'city': 'Lynchburg', 'timezone': 'EST'},
            '435': {'state': 'Utah', 'city': 'Logan', 'timezone': 'MST'},
            '440': {'state': 'Ohio', 'city': 'Cleveland', 'timezone': 'EST'},
            '442': {'state': 'California', 'city': 'Oceanside', 'timezone': 'PST'},
            '443': {'state': 'Maryland', 'city': 'Baltimore', 'timezone': 'EST'},
            '445': {'state': 'Pennsylvania', 'city': 'Philadelphia', 'timezone': 'EST'},
            '447': {'state': 'Illinois', 'city': 'Springfield', 'timezone': 'CST'},
            '458': {'state': 'Oregon', 'city': 'Eugene', 'timezone': 'PST'},
            '463': {'state': 'Indiana', 'city': 'Indianapolis', 'timezone': 'EST'},
            '464': {'state': 'Illinois', 'city': 'Chicago', 'timezone': 'CST'},
            '469': {'state': 'Texas', 'city': 'Dallas', 'timezone': 'CST'},
            '470': {'state': 'Georgia', 'city': 'Atlanta', 'timezone': 'EST'},
            '475': {'state': 'Connecticut', 'city': 'Bridgeport', 'timezone': 'EST'},
            '478': {'state': 'Georgia', 'city': 'Macon', 'timezone': 'EST'},
            '479': {'state': 'Arkansas', 'city': 'Fort Smith', 'timezone': 'CST'},
            '480': {'state': 'Arizona', 'city': 'Phoenix', 'timezone': 'MST'},
            '484': {'state': 'Pennsylvania', 'city': 'Allentown', 'timezone': 'EST'},
            '501': {'state': 'Arkansas', 'city': 'Little Rock', 'timezone': 'CST'},
            '502': {'state': 'Kentucky', 'city': 'Louisville', 'timezone': 'EST'},
            '503': {'state': 'Oregon', 'city': 'Portland', 'timezone': 'PST'},
            '504': {'state': 'Louisiana', 'city': 'New Orleans', 'timezone': 'CST'},
            '505': {'state': 'New Mexico', 'city': 'Albuquerque', 'timezone': 'MST'},
            '507': {'state': 'Minnesota', 'city': 'Rochester', 'timezone': 'CST'},
            '508': {'state': 'Massachusetts', 'city': 'Worcester', 'timezone': 'EST'},
            '509': {'state': 'Washington', 'city': 'Spokane', 'timezone': 'PST'},
            '510': {'state': 'California', 'city': 'Oakland', 'timezone': 'PST'},
            '512': {'state': 'Texas', 'city': 'Austin', 'timezone': 'CST'},
            '513': {'state': 'Ohio', 'city': 'Cincinnati', 'timezone': 'EST'},
            '515': {'state': 'Iowa', 'city': 'Des Moines', 'timezone': 'CST'},
            '516': {'state': 'New York', 'city': 'Hempstead', 'timezone': 'EST'},
            '517': {'state': 'Michigan', 'city': 'Lansing', 'timezone': 'EST'},
            '518': {'state': 'New York', 'city': 'Albany', 'timezone': 'EST'},
            '520': {'state': 'Arizona', 'city': 'Tucson', 'timezone': 'MST'},
            '530': {'state': 'California', 'city': 'Redding', 'timezone': 'PST'},
            '531': {'state': 'Nebraska', 'city': 'Omaha', 'timezone': 'CST'},
            '534': {'state': 'Wisconsin', 'city': 'Green Bay', 'timezone': 'CST'},
            '539': {'state': 'Oklahoma', 'city': 'Tulsa', 'timezone': 'CST'},
            '540': {'state': 'Virginia', 'city': 'Roanoke', 'timezone': 'EST'},
            '541': {'state': 'Oregon', 'city': 'Eugene', 'timezone': 'PST'},
            '551': {'state': 'New Jersey', 'city': 'Hackensack', 'timezone': 'EST'},
            '559': {'state': 'California', 'city': 'Fresno', 'timezone': 'PST'},
            '561': {'state': 'Florida', 'city': 'West Palm Beach', 'timezone': 'EST'},
            '562': {'state': 'California', 'city': 'Long Beach', 'timezone': 'PST'},
            '563': {'state': 'Iowa', 'city': 'Davenport', 'timezone': 'CST'},
            '564': {'state': 'Washington', 'city': 'Everett', 'timezone': 'PST'},
            '567': {'state': 'Ohio', 'city': 'Toledo', 'timezone': 'EST'},
            '570': {'state': 'Pennsylvania', 'city': 'Scranton', 'timezone': 'EST'},
            '571': {'state': 'Virginia', 'city': 'Arlington', 'timezone': 'EST'},
            '573': {'state': 'Missouri', 'city': 'Columbia', 'timezone': 'CST'},
            '574': {'state': 'Indiana', 'city': 'South Bend', 'timezone': 'EST'},
            '575': {'state': 'New Mexico', 'city': 'Las Cruces', 'timezone': 'MST'},
            '580': {'state': 'Oklahoma', 'city': 'Lawton', 'timezone': 'CST'},
            '585': {'state': 'New York', 'city': 'Rochester', 'timezone': 'EST'},
            '586': {'state': 'Michigan', 'city': 'Warren', 'timezone': 'EST'},
            '601': {'state': 'Mississippi', 'city': 'Jackson', 'timezone': 'CST'},
            '602': {'state': 'Arizona', 'city': 'Phoenix', 'timezone': 'MST'},
            '603': {'state': 'New Hampshire', 'city': 'Manchester', 'timezone': 'EST'},
            '605': {'state': 'South Dakota', 'city': 'Sioux Falls', 'timezone': 'CST'},
            '606': {'state': 'Kentucky', 'city': 'Ashland', 'timezone': 'EST'},
            '607': {'state': 'New York', 'city': 'Binghamton', 'timezone': 'EST'},
            '608': {'state': 'Wisconsin', 'city': 'Madison', 'timezone': 'CST'},
            '609': {'state': 'New Jersey', 'city': 'Trenton', 'timezone': 'EST'},
            '610': {'state': 'Pennsylvania', 'city': 'Allentown', 'timezone': 'EST'},
            '612': {'state': 'Minnesota', 'city': 'Minneapolis', 'timezone': 'CST'},
            '614': {'state': 'Ohio', 'city': 'Columbus', 'timezone': 'EST'},
            '615': {'state': 'Tennessee', 'city': 'Nashville', 'timezone': 'CST'},
            '616': {'state': 'Michigan', 'city': 'Grand Rapids', 'timezone': 'EST'},
            '617': {'state': 'Massachusetts', 'city': 'Boston', 'timezone': 'EST'},
            '618': {'state': 'Illinois', 'city': 'Carbondale', 'timezone': 'CST'},
            '619': {'state': 'California', 'city': 'San Diego', 'timezone': 'PST'},
            '620': {'state': 'Kansas', 'city': 'Hutchinson', 'timezone': 'CST'},
            '623': {'state': 'Arizona', 'city': 'Phoenix', 'timezone': 'MST'},
            '626': {'state': 'California', 'city': 'Pasadena', 'timezone': 'PST'},
            '628': {'state': 'California', 'city': 'San Francisco', 'timezone': 'PST'},
            '629': {'state': 'Tennessee', 'city': 'Nashville', 'timezone': 'CST'},
            '630': {'state': 'Illinois', 'city': 'Aurora', 'timezone': 'CST'},
            '631': {'state': 'New York', 'city': 'Huntington', 'timezone': 'EST'},
            '636': {'state': 'Missouri', 'city': 'O\'Fallon', 'timezone': 'CST'},
            '641': {'state': 'Iowa', 'city': 'Mason City', 'timezone': 'CST'},
            '646': {'state': 'New York', 'city': 'New York', 'timezone': 'EST'},
            '650': {'state': 'California', 'city': 'San Mateo', 'timezone': 'PST'},
            '651': {'state': 'Minnesota', 'city': 'St. Paul', 'timezone': 'CST'},
            '657': {'state': 'California', 'city': 'Anaheim', 'timezone': 'PST'},
            '660': {'state': 'Missouri', 'city': 'Sedalia', 'timezone': 'CST'},
            '661': {'state': 'California', 'city': 'Bakersfield', 'timezone': 'PST'},
            '662': {'state': 'Mississippi', 'city': 'Tupelo', 'timezone': 'CST'},
            '667': {'state': 'Maryland', 'city': 'Baltimore', 'timezone': 'EST'},
            '669': {'state': 'California', 'city': 'San Jose', 'timezone': 'PST'},
            '678': {'state': 'Georgia', 'city': 'Atlanta', 'timezone': 'EST'},
            '681': {'state': 'West Virginia', 'city': 'Charleston', 'timezone': 'EST'},
            '682': {'state': 'Texas', 'city': 'Fort Worth', 'timezone': 'CST'},
            '701': {'state': 'North Dakota', 'city': 'Fargo', 'timezone': 'CST'},
            '702': {'state': 'Nevada', 'city': 'Las Vegas', 'timezone': 'PST'},
            '703': {'state': 'Virginia', 'city': 'Arlington', 'timezone': 'EST'},
            '704': {'state': 'North Carolina', 'city': 'Charlotte', 'timezone': 'EST'},
            '706': {'state': 'Georgia', 'city': 'Columbus', 'timezone': 'EST'},
            '707': {'state': 'California', 'city': 'Santa Rosa', 'timezone': 'PST'},
            '708': {'state': 'Illinois', 'city': 'Cicero', 'timezone': 'CST'},
            '712': {'state': 'Iowa', 'city': 'Sioux City', 'timezone': 'CST'},
            '713': {'state': 'Texas', 'city': 'Houston', 'timezone': 'CST'},
            '714': {'state': 'California', 'city': 'Anaheim', 'timezone': 'PST'},
            '715': {'state': 'Wisconsin', 'city': 'Eau Claire', 'timezone': 'CST'},
            '716': {'state': 'New York', 'city': 'Buffalo', 'timezone': 'EST'},
            '717': {'state': 'Pennsylvania', 'city': 'Lancaster', 'timezone': 'EST'},
            '718': {'state': 'New York', 'city': 'Brooklyn', 'timezone': 'EST'},
            '719': {'state': 'Colorado', 'city': 'Colorado Springs', 'timezone': 'MST'},
            '720': {'state': 'Colorado', 'city': 'Denver', 'timezone': 'MST'},
            '724': {'state': 'Pennsylvania', 'city': 'New Castle', 'timezone': 'EST'},
            '725': {'state': 'Nevada', 'city': 'Las Vegas', 'timezone': 'PST'},
            '727': {'state': 'Florida', 'city': 'St. Petersburg', 'timezone': 'EST'},
            '731': {'state': 'Tennessee', 'city': 'Jackson', 'timezone': 'CST'},
            '732': {'state': 'New Jersey', 'city': 'New Brunswick', 'timezone': 'EST'},
            '734': {'state': 'Michigan', 'city': 'Ann Arbor', 'timezone': 'EST'},
            '737': {'state': 'Texas', 'city': 'Austin', 'timezone': 'CST'},
            '740': {'state': 'Ohio', 'city': 'Zanesville', 'timezone': 'EST'},
            '743': {'state': 'North Carolina', 'city': 'Greensboro', 'timezone': 'EST'},
            '747': {'state': 'California', 'city': 'Burbank', 'timezone': 'PST'},
            '754': {'state': 'Florida', 'city': 'Fort Lauderdale', 'timezone': 'EST'},
            '757': {'state': 'Virginia', 'city': 'Virginia Beach', 'timezone': 'EST'},
            '760': {'state': 'California', 'city': 'Oceanside', 'timezone': 'PST'},
            '762': {'state': 'Georgia', 'city': 'Columbus', 'timezone': 'EST'},
            '763': {'state': 'Minnesota', 'city': 'Brooklyn Park', 'timezone': 'CST'},
            '765': {'state': 'Indiana', 'city': 'Muncie', 'timezone': 'EST'},
            '769': {'state': 'Mississippi', 'city': 'Jackson', 'timezone': 'CST'},
            '770': {'state': 'Georgia', 'city': 'Marietta', 'timezone': 'EST'},
            '772': {'state': 'Florida', 'city': 'Port St. Lucie', 'timezone': 'EST'},
            '773': {'state': 'Illinois', 'city': 'Chicago', 'timezone': 'CST'},
            '774': {'state': 'Massachusetts', 'city': 'Worcester', 'timezone': 'EST'},
            '775': {'state': 'Nevada', 'city': 'Reno', 'timezone': 'PST'},
            '779': {'state': 'Illinois', 'city': 'Rockford', 'timezone': 'CST'},
            '781': {'state': 'Massachusetts', 'city': 'Boston', 'timezone': 'EST'},
            '785': {'state': 'Kansas', 'city': 'Topeka', 'timezone': 'CST'},
            '786': {'state': 'Florida', 'city': 'Miami', 'timezone': 'EST'},
            '787': {'state': 'Puerto Rico', 'city': 'San Juan', 'timezone': 'AST'},
            '801': {'state': 'Utah', 'city': 'Salt Lake City', 'timezone': 'MST'},
            '802': {'state': 'Vermont', 'city': 'Burlington', 'timezone': 'EST'},
            '804': {'state': 'Virginia', 'city': 'Richmond', 'timezone': 'EST'},
            '805': {'state': 'California', 'city': 'Oxnard', 'timezone': 'PST'},
            '806': {'state': 'Texas', 'city': 'Lubbock', 'timezone': 'CST'},
            '808': {'state': 'Hawaii', 'city': 'Honolulu', 'timezone': 'HST'},
            '810': {'state': 'Michigan', 'city': 'Flint', 'timezone': 'EST'},
            '812': {'state': 'Indiana', 'city': 'Evansville', 'timezone': 'CST'},
            '813': {'state': 'Florida', 'city': 'Tampa', 'timezone': 'EST'},
            '814': {'state': 'Pennsylvania', 'city': 'Erie', 'timezone': 'EST'},
            '815': {'state': 'Illinois', 'city': 'Rockford', 'timezone': 'CST'},
            '816': {'state': 'Missouri', 'city': 'Kansas City', 'timezone': 'CST'},
            '817': {'state': 'Texas', 'city': 'Fort Worth', 'timezone': 'CST'},
            '818': {'state': 'California', 'city': 'Burbank', 'timezone': 'PST'},
            '828': {'state': 'North Carolina', 'city': 'Asheville', 'timezone': 'EST'},
            '830': {'state': 'Texas', 'city': 'New Braunfels', 'timezone': 'CST'},
            '831': {'state': 'California', 'city': 'Salinas', 'timezone': 'PST'},
            '832': {'state': 'Texas', 'city': 'Houston', 'timezone': 'CST'},
            '843': {'state': 'South Carolina', 'city': 'Charleston', 'timezone': 'EST'},
            '845': {'state': 'New York', 'city': 'Poughkeepsie', 'timezone': 'EST'},
            '847': {'state': 'Illinois', 'city': 'Evanston', 'timezone': 'CST'},
            '848': {'state': 'New Jersey', 'city': 'New Brunswick', 'timezone': 'EST'},
            '850': {'state': 'Florida', 'city': 'Tallahassee', 'timezone': 'EST'},
            '856': {'state': 'New Jersey', 'city': 'Camden', 'timezone': 'EST'},
            '857': {'state': 'Massachusetts', 'city': 'Boston', 'timezone': 'EST'},
            '858': {'state': 'California', 'city': 'San Diego', 'timezone': 'PST'},
            '859': {'state': 'Kentucky', 'city': 'Lexington', 'timezone': 'EST'},
            '860': {'state': 'Connecticut', 'city': 'Hartford', 'timezone': 'EST'},
            '862': {'state': 'New Jersey', 'city': 'Newark', 'timezone': 'EST'},
            '863': {'state': 'Florida', 'city': 'Lakeland', 'timezone': 'EST'},
            '864': {'state': 'South Carolina', 'city': 'Greenville', 'timezone': 'EST'},
            '865': {'state': 'Tennessee', 'city': 'Knoxville', 'timezone': 'EST'},
            '870': {'state': 'Arkansas', 'city': 'Jonesboro', 'timezone': 'CST'},
            '872': {'state': 'Illinois', 'city': 'Chicago', 'timezone': 'CST'},
            '878': {'state': 'Pennsylvania', 'city': 'Pittsburgh', 'timezone': 'EST'},
            '901': {'state': 'Tennessee', 'city': 'Memphis', 'timezone': 'CST'},
            '903': {'state': 'Texas', 'city': 'Tyler', 'timezone': 'CST'},
            '904': {'state': 'Florida', 'city': 'Jacksonville', 'timezone': 'EST'},
            '906': {'state': 'Michigan', 'city': 'Marquette', 'timezone': 'EST'},
            '907': {'state': 'Alaska', 'city': 'Anchorage', 'timezone': 'AKST'},
            '908': {'state': 'New Jersey', 'city': 'Elizabeth', 'timezone': 'EST'},
            '909': {'state': 'California', 'city': 'San Bernardino', 'timezone': 'PST'},
            '910': {'state': 'North Carolina', 'city': 'Fayetteville', 'timezone': 'EST'},
            '912': {'state': 'Georgia', 'city': 'Savannah', 'timezone': 'EST'},
            '913': {'state': 'Kansas', 'city': 'Overland Park', 'timezone': 'CST'},
            '914': {'state': 'New York', 'city': 'Yonkers', 'timezone': 'EST'},
            '915': {'state': 'Texas', 'city': 'El Paso', 'timezone': 'MST'},
            '916': {'state': 'California', 'city': 'Sacramento', 'timezone': 'PST'},
            '917': {'state': 'New York', 'city': 'New York', 'timezone': 'EST'},
            '918': {'state': 'Oklahoma', 'city': 'Tulsa', 'timezone': 'CST'},
            '919': {'state': 'North Carolina', 'city': 'Raleigh', 'timezone': 'EST'},
            '920': {'state': 'Wisconsin', 'city': 'Green Bay', 'timezone': 'CST'},
            '925': {'state': 'California', 'city': 'Concord', 'timezone': 'PST'},
            '928': {'state': 'Arizona', 'city': 'Flagstaff', 'timezone': 'MST'},
            '929': {'state': 'New York', 'city': 'Bronx', 'timezone': 'EST'},
            '930': {'state': 'Indiana', 'city': 'New Albany', 'timezone': 'EST'},
            '931': {'state': 'Tennessee', 'city': 'Clarksville', 'timezone': 'CST'},
            '934': {'state': 'New York', 'city': 'Huntington', 'timezone': 'EST'},
            '936': {'state': 'Texas', 'city': 'Huntsville', 'timezone': 'CST'},
            '937': {'state': 'Ohio', 'city': 'Dayton', 'timezone': 'EST'},
            '940': {'state': 'Texas', 'city': 'Wichita Falls', 'timezone': 'CST'},
            '941': {'state': 'Florida', 'city': 'Sarasota', 'timezone': 'EST'},
            '947': {'state': 'Michigan', 'city': 'Troy', 'timezone': 'EST'},
            '949': {'state': 'California', 'city': 'Irvine', 'timezone': 'PST'},
            '951': {'state': 'California', 'city': 'Riverside', 'timezone': 'PST'},
            '952': {'state': 'Minnesota', 'city': 'Bloomington', 'timezone': 'CST'},
            '954': {'state': 'Florida', 'city': 'Fort Lauderdale', 'timezone': 'EST'},
            '956': {'state': 'Texas', 'city': 'Laredo', 'timezone': 'CST'},
            '959': {'state': 'Connecticut', 'city': 'Hartford', 'timezone': 'EST'},
            '970': {'state': 'Colorado', 'city': 'Fort Collins', 'timezone': 'MST'},
            '971': {'state': 'Oregon', 'city': 'Portland', 'timezone': 'PST'},
            '972': {'state': 'Texas', 'city': 'Dallas', 'timezone': 'CST'},
            '973': {'state': 'New Jersey', 'city': 'Newark', 'timezone': 'EST'},
            '978': {'state': 'Massachusetts', 'city': 'Lowell', 'timezone': 'EST'},
            '979': {'state': 'Texas', 'city': 'Bryan', 'timezone': 'CST'},
            '980': {'state': 'North Carolina', 'city': 'Charlotte', 'timezone': 'EST'},
            '984': {'state': 'North Carolina', 'city': 'Raleigh', 'timezone': 'EST'},
            '985': {'state': 'Louisiana', 'city': 'Hammond', 'timezone': 'CST'},
            '989': {'state': 'Michigan', 'city': 'Saginaw', 'timezone': 'EST'}
        }

        if area_code in area_code_data:
            data = area_code_data[area_code]
            return {
                'area_code': area_code,
                'state': data['state'],
                'city': data['city'],
                'timezone': data['timezone'],
                'country': 'US',
                'source': 'local_database'
            }
        else:
            return {
                'area_code': area_code,
                'error': 'Area code not found in database',
                'source': 'local_database'
            }
