name = "project-revelare-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (non-sensitive)
[vars]
NODE_ENV = "production"
API_VERSION = "v1"
ALLOWED_ORIGINS = "https://project-revelare.com,https://project-revelare-web.pages.dev"

# KV Storage for sessions and caching (global fallback)
[[kv_namespaces]]
binding = "REVELARE_KV"
id = "1240af71a32f4e4aaaeb7b0cd508ca86"
preview_id = "1240af71a32f4e4aaaeb7b0cd508ca86"

# R2 Storage for file uploads (global fallback)
[[r2_buckets]]
binding = "R2_EVIDENCE_BUCKET"
bucket_name = "revelare-evidence"

# D1 Database (global fallback)
[[d1_databases]]
binding = "DB"
database_name = "revelare-db"
database_id = "609cd112-f50c-4c98-be81-8a818f835ad1"

# Environment-specific configurations
[env.staging]
name = "project-revelare-backend-staging"
routes = [
  "https://staging-api.project-revelare.com/*"
]

[env.staging.vars]
NODE_ENV = "staging"
API_VERSION = "v1"
ALLOWED_ORIGINS = "https://project-revelare.com,https://project-revelare-web.pages.dev"

[env.production]
name = "project-revelare-backend-prod"
routes = [
  "https://api.project-revelare.com/*"
]

[env.production.vars]
NODE_ENV = "production"
API_VERSION = "v1"
ALLOWED_ORIGINS = "https://project-revelare.com,https://project-revelare-web.pages.dev"

# Durable Objects for session management (optional)
# [[durable_objects.bindings]]
# name = "SESSION_STORE"
# class_name = "SessionStore"

# Placement configuration
[placement]
mode = "smart"

# Build configuration
[build]
command = "npm run build"

# Worker configuration
[worker]
memory_limit = "512 MB"
cpu_limit = 1000
